"""empty message

Revision ID: a13ab7df2bd2
Revises: 6fef156ef8be
Create Date: 2021-12-23 20:52:32.372029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13ab7df2bd2'
down_revision = '6fef156ef8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('full_address', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('suburb', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('state', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('postcode', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('bedrooms', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('bathrooms', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('parking_spaces', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('building_size', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('building_size_unit', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('land_size', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('land_size_unit', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('listing_company_name', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('sold_date', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('listing_download_date', sa.String(), nullable=True))
    op.drop_column('houses', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('houses', 'listing_download_date')
    op.drop_column('houses', 'description')
    op.drop_column('houses', 'sold_date')
    op.drop_column('houses', 'listing_company_name')
    op.drop_column('houses', 'land_size_unit')
    op.drop_column('houses', 'land_size')
    op.drop_column('houses', 'building_size_unit')
    op.drop_column('houses', 'building_size')
    op.drop_column('houses', 'parking_spaces')
    op.drop_column('houses', 'bathrooms')
    op.drop_column('houses', 'bedrooms')
    op.drop_column('houses', 'postcode')
    op.drop_column('houses', 'state')
    op.drop_column('houses', 'suburb')
    op.drop_column('houses', 'full_address')
    # ### end Alembic commands ###
